### PR TITLE
Add Stalebot and No-Response Action Config

### PR DESCRIPTION
**Pull request by sighphyre**
This adds two configuration files for Stalebot and the No-Response Action (No-Response bot has been deprecated and the No-Response Action is the recommended alternative).

The No-Response Action config has been left as default (more details on the defaults can be found here: https://github.com/lee-dohm/no-response/blob/main/action.yml and more details on the action itself in the root project).

The stalebot config has been slightly altered (original config here: https://github.com/probot/stale). Notably, the message for PRs and Issues has been customised and the time until being marked as stale has been reduced from 60 days to 30. Default config for exempt issues remains, which means that issues that are pinned, marked with a security label or a "[Status] Maybe Later" label won't be marked as stale

### CODE REVIEW

**Comment by sighphyre** [comment]
[go through all github issues  / PRs in all repos](https://trello.com/c/OI7cp2pH/1027-go-through-all-github-issues-prs-in-all-repos)

**Comment by sighphyre** [comment]
[go through all github issues  / PRs in all repos](https://trello.com/c/OI7cp2pH/1027-go-through-all-github-issues-prs-in-all-repos)

**Comment by sighphyre** [comment]
[go through all github issues  / PRs in all repos](https://trello.com/c/OI7cp2pH/1027-go-through-all-github-issues-prs-in-all-repos)

**Review by thomasheartman — APPROVED** [review]
Looks good to me! Nice work 🙌🏼  My only question is that you mention that the stalebot messages have been tweaked: what have you changed? I tried to compare them, but couldn't tell what was different 🙈

**Comment by sighphyre** [comment]
@thomasheartman The message is a tiny change - by default you get the same message for a PR and an Issue, the change here just changes "PR" to "Issue" in the text when it's dealing with an Issue

**Comment by thomasheartman** [comment]
@sighphyre Ah, got it! I thought they were two separate ones already. Thanks for clarifying!

**Pull request merged**
