### PR TITLE
Docs: restructure documentation

### PR DESCRIPTION
**Pull request by thomasheartman**
this PR completely changes how the documentation is structured. The changes are all based on the [Diataxis documentation framework](https://diataxis.fr/).

Importantly, it:

- Removes the separate pages for deployment, API, and integrations
- Organizes all documents into one of four categories (with optional subcategories)
- Creates a new landing page / doc

### CODE REVIEW

**Comment by thomasheartman** [comment]
[Restructure documentation](https://trello.com/c/SWlV1hTO/681-restructure-documentation)

**Comment by ivarconr** [comment]
I find it a bit strange that SSO starts with a deprecated guide:
image

Also, we should probably have a general overview for SSO. Lets create a issue for that!

**Comment by ivarconr** [comment]
It would be good if the new landing page could include a few more quick-links. 

E.g I found it a bit hard to figure out where the API docs where.

**Comment by ivarconr** [comment]
I really like this HOWTO overview page:

image

Maybe we can do similar things for other categories, and even the landing page?

**Comment by thomasheartman** [comment]
@ivarconr Thanks; that's great! Let me give some quick responses:

> I find it a bit strange that SSO starts with a deprecated guide:
> [...]
> Also, we should probably have a general overview for SSO. Lets create a issue for that!

Yes, I agree it's strange, but I'm not sure how to best deal with it. I ended up doing it this way because it's alphabetical. It might be worth finding another way of doing it.

And yeah, the overview page would be good! Either as an article or as the how-to overview page.

> I really like this HOWTO overview page:
> [...]
> Maybe we can do similar things for other categories, and even the landing page?

Absolutely! That's a thing docusaurus can do automatically, so it's super easy to set up. I was just playing around with the idea. I agree that we should/could have similar landing pages for other categories. There might even be a nice way to integrate it into the landing page. I'll have a look 🙋🏼 

> It would be good if the new landing page could include a few more quick-links.
> E.g I found it a bit hard to figure out where the API docs where.

Great point! And super feedback. I haven't added links in there yet, but having links directly to first-level subcategories is probably a really good idea.

**Comment by thomasheartman** [comment]
[Docs restructure: add landing pages for categories](https://trello.com/c/5dSwDAMq/781-docs-restructure-add-landing-pages-for-categories)

**Comment by thomasheartman** [comment]
[Docs restructure: create first-level overview on landing page (with links)](https://trello.com/c/ciafwM5M/782-docs-restructure-create-first-level-overview-on-landing-page-with-links)

**Comment by thomasheartman** [comment]
[Docs restructure: Add old version of docs at a separate path](https://trello.com/c/X54J5ppz/783-docs-restructure-add-old-version-of-docs-at-a-separate-path)

**Comment by thomasheartman** [comment]
[Docs restructure: add Unleash squares as category markers in sidebar](https://trello.com/c/KpxYs4hf/784-docs-restructure-add-unleash-squares-as-category-markers-in-sidebar)

**Review by ivarconr — APPROVED** [review]

**Pull request merged**
