### PR TITLE
task: add sdk version metric

### PR DESCRIPTION
**Pull request by chriswk**
So I know we have this in the database, but it's come up a couple of times in user discussions where the user asks how they're supposed to keep track of which SDK versions are being used. I don't think we currently expose a top level sdk version usage, so you need access to the database to do your own queries for figuring out which sdk version strings the server has seen.

This PR exposes this as a prometheus metric.

I'm a tad worried about the cardinality of this metric, but I've at least made sure that a client registration needs to include an sdkVersion field in the format `<sdkName>:<sdkVersion>`. So as to not accept anything into the labels for the metric. 

Maybe it would be better to parse the <sdkVersion> using the semantic library and then use major, minor, patch as separate labels. That would require all sdk's that register with sdkVersion to pass in a SemVer compatible version.

### CODE REVIEW

**Comment by sighphyre** [comment]
@chriswk Outside of running a custom/dev build, all the SDKs should send semver compatible versions, if they aren't, that's a bug and/or someone's done something weird. So it should be safe to depend on, so long as you account for potentially also occasionally getting nonsense there.

**Comment by thomasheartman** [comment]
I'm not sure I have all the context I need to give the best feedback on this, but it sounds sensible to me. Is there more information available about this somewhere? If not, would you mind explaining a bit more:
- How is it exposed as a prometheus metric? We have an endpoint for that, don't we? Is the payload just updated? I'm not very familiar with prometheus.
- Why are you afraid of the cardinality of the metric? Because for each SDK version, the user could have any number of different versions?
- Parsing using the `semantic` library sounds good to me, but what would it offer us? What are the pros and cons?

**Review by sighphyre — APPROVED** [review]
LGTM

**Comment by chriswk** [comment]
> I'm not sure I have all the context I need to give the best feedback on this, but it sounds sensible to me. Is there more information available about this somewhere? If not, would you mind explaining a bit more:
> 
> * How is it exposed as a prometheus metric? We have an endpoint for that, don't we? Is the payload just updated? I'm not very familiar with prometheus.
Prometheus is a pull-based system, so a prometheus server polls unleash at `<contextpath>/internal-backstage/prometheus`.

> * Why are you afraid of the cardinality of the metric? Because for each SDK version, the user could have any number of different versions?
The number of metrics here will be <sdk> * <version>, so potentially if we have lots of different sdks connecting we could add 100s of lines to the prometheus output.

> * Parsing using the `semantic` library sounds good to me, but what would it offer us? What are the pros and cons?
It would allow us to create more labels (major, minor, patch) to build more graphs in grafana for it. I think this can be added later.

**Pull request merged**
