### PR TITLE
fix: cherry pick security fixes

### PR DESCRIPTION
**Pull request by gastonfournier**

### CODE REVIEW

**Review by nunogois — APPROVED** [review]
What's up with the failing check?

**Comment by gastonfournier** [comment]
> What's up with the failing check?

I have no idea, I was curious about the same because in main it works well: https://github.com/Unleash/unleash/actions/runs/10924175490/job/30322576604

I'll take a look

**Comment by gastonfournier** [comment]
The thing is that both Apache 2.0 and MIT are accepted in our branch https://github.com/Unleash/unleash/blob/6.2/.github/workflows/dependency-review.yml#L20:
image

**Comment by gastonfournier** [comment]
Also, the diff: 
```
git diff origin/main -- yarn.lock package.json
```
```diff
diff --git a/package.json b/package.json
index d28284851..e9b6b6093 100644
--- a/package.json
+++ b/package.json
@@ -58,7 +58,6 @@
     "test:watch": "yarn test --watch",
     "test:coverage": "NODE_ENV=test PORT=4243 jest --coverage --testLocationInResults --outputFile=\"coverage/report.json\" --forceExit --testTimeout=10000",
     "test:coverage:jest": "NODE_ENV=test PORT=4243 jest --silent --ci --json --coverage --testLocationInResults --outputFile=\"report.json\" --forceExit --testTimeout=10000",
-    "test:updateSnapshot": "NODE_ENV=test PORT=4243 jest --updateSnapshot --testTimeout=10000",
     "seed:setup": "ts-node --compilerOptions '{\"strictNullChecks\": false}' src/test/e2e/seed/segment.seed.ts",
     "seed:serve": "UNLEASH_DATABASE_NAME=unleash_test UNLEASH_DATABASE_SCHEMA=seed yarn run start:dev",
     "clean": "del-cli --force dist",
```

**Pull request merged**
