### PR TITLE
implement proxy all endpoint

### PR DESCRIPTION
**Pull request by andreas-unleash**
Signed-off-by: andreas-unleash <andreas@getunleash.ai>

This PR implements the `all` endpoint of unleash-proxy, by adding an experimental flag that can control the behaviour

## About the changes

Closes #

### CODE REVIEW

**Review by thomasheartman — CHANGES_REQUESTED** [review]
Nice! This looks pretty great 😄 I just have few questions and cases we should test inline. Let me know what you think 🙌🏼

**Review by FredrikOseberg — CHANGES_REQUESTED** [review]
We dont control the query parameter in the SDK. Doing this with a query parameter would require us to make changes in all client SDKs. i would prefer if this was a setting in Unleash instead.

**Review by FredrikOseberg — APPROVED** [review]
LGTM. Just need to fix prettier to pass the checks.

**Review by thomasheartman — APPROVED** [review]
Nice work 💯

**Pull request merged**
