### PR TITLE
Fix: update docker directory yarn lock file

### LINKED ISSUE #4795: string-width dependency stops unleash from executing
### Describe the bug

Docker image keeps exiting for string-width dependency error

### Steps to reproduce the bug

make docker compose to work with repositories docker file:
```-    image: unleashorg/unleash-server:latest
+    build:
+      context: .
+      dockerfile: Dockerfile```
Build and run:
`$ docker compose up -d --build`
Checkout the log:
`$ docker logs unleash-web-1`

### Expected behavior

Run without exceptions

### Logs, error output, etc.

```bash
[2023-09-20T12:12:47.366] [ERROR] server-impl.js - Failed to migrate db Error [ERR_REQUIRE_ESM]: require() of ES Module /unleash/node_modules/string-width/index.js from /unleash/node_modules/yargs/build/lib/usage.js not supported.
Instead change the require of index.js in /unleash/node_modules/yargs/build/lib/usage.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/unleash/node_modules/yargs/build/lib/usage.js:12:21)
    at Object.<anonymous> (/unleash/node_modules/yargs/build/lib/yargs.js:7:17)
    at Object.<anonymous> (/unleash/node_modules/yargs/yargs.js:7:27)
    at Object.<anonymous> (/unleash/node_modules/yargs/index.js:5:15)
    at Object.<anonymous> (/unleash/node_modules/db-migrate/lib/commands/set-default-argv.js:1:13)
    at register (/unleash/node_modules/db-migrate/lib/commands/index.js:6:10)
    at new dbmigrate (/unleash/node_modules/db-migrate/api.js:27:24)
    at module.exports.getInstance (/unleash/node_modules/db-migrate/index.js:85:10)
    at migrateDb (/unleash/node_modules/unleash-server/dist/migrator.js:15:46)
    at Object.start (/unleash/node_modules/unleash-server/dist/lib/server-impl.js:158:48)
    at Object.<anonymous> (/unleash/index.js:7:9) {
  code: 'ERR_REQUIRE_ESM'
}
/unleash/node_modules/yargs/build/lib/usage.js:12
const stringWidth = require("string-width");
                    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /unleash/node_modules/string-width/index.js from /unleash/node_modules/yargs/build/lib/usage.js not supported.
Instead change the require of index.js in /unleash/node_modules/yargs/build/lib/usage.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/unleash/node_modules/yargs/build/lib/usage.js:12:21)
    at Object.<anonymous> (/unleash/node_modules/yargs/build/lib/yargs.js:7:17)
    at Object.<anonymous> (/unleash/node_modules/yargs/yargs.js:7:27)
    at Object.<anonymous> (/unleash/node_modules/yargs/index.js:5:15)
    at Object.<anonymous> (/unleash/node_modules/db-migrate/lib/commands/set-default-argv.js:1:13)
    at register (/unleash/node_modules/db-migrate/lib/commands/index.js:6:10)
    at new dbmigrate (/unleash/node_modules/db-migrate/api.js:27:24)
    at module.exports.getInstance (/unleash/node_modules/db-migrate/index.js:85:10)
    at migrateDb (/unleash/node_modules/unleash-server/dist/migrator.js:15:46)
    at Object.start (/unleash/node_modules/unleash-server/dist/lib/server-impl.js:158:48)
    at Object.<anonymous> (/unleash/index.js:7:9) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.18.0```
```

### Screenshots

_No response_

### Additional context

_No response_

### Unleash version

lastest main commit: 1e66d2aca914c70af4c58a1602ecd72c16f616e6

### Subscription type

Open source

### Hosting type

Self-hosted

### SDK information (language and version)

_No response_

### PR DESCRIPTION
**Pull request by pmahdavii**
## About the changes
Updated docker/yarn.lock by running `yarn install --production=true` witch is used with `--frozen-lockfile` flag in the dockerfile.

Closes #4795

### Important files
- docker/yarn.lock

### CODE REVIEW

**Comment by snosratiershad** [comment]
I've pair-tested the patch with dear @pmahdavii and it works.

**Comment by kwasniew** [comment]
@pmahdavii and @snosratiershad what yarn version did you use? I've run: `yarn install --production=true` on yarn 1.22.19 which is the one used by Docker and my lockfile is 10 times bigger than yours.

**Comment by gardleopard** [comment]
We have merged this fix for this issue now https://github.com/Unleash/unleash/pull/4808

**Comment by kwasniew** [comment]
@pmahdavii and @snosratiershad I'd like to thank you for your research that helped us quickly solve the problem.

**Comment by snosratiershad** [comment]
Thank you @kwasniew

**Pull request closed without merging**
