### PR TITLE
Added ability to set additional transport options to email service

### LINKED ISSUE #1583: Can not connect to SMTP without credentials
### Describe the bug

Our SMTP server does not require a username and password, but when leaving the fields blank the unleash email service tries to connect to smtp like this: `smtp://undefined:undefined@host:port`

### Steps to reproduce the bug

```
unleash
  .start({
    email: {
      host: process.env.EMAIL_HOST,
      port: process.env.EMAIL_PORT,
      sender: process.env.EMAIL_SENDER
    }
  })
  .then((unleash) => {
    console.log(
      `Unleash started on port ${unleash.app.get('port')}`,
    );
  });
```

### Expected behavior

Unleash email service should connect to `smtp://host:port`

### Logs, error output, etc.

_No response_

### Screenshots

```
[2022-05-10T11:02:51.445] [INFO] services/email-service.ts - Initialized transport to XXX.XXX.XXX.XXX on port 25 with user: undefined

[2022-05-10T12:08:00.079] [WARN] services/email-service.ts - Failed to send getting started email Error: Connection timeout
    at SMTPConnection._formatError (/Users/251743/Documents/helios-unleash/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
    at SMTPConnection._onError (/Users/251743/Documents/helios-unleash/node_modules/nodemailer/lib/smtp-connection/index.js:770:20)
    at Timeout.<anonymous> (/Users/251743/Documents/helios-unleash/node_modules/nodemailer/lib/smtp-connection/index.js:229:22)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  code: 'ETIMEDOUT',
  command: 'CONN'
}
```

### Additional context

_No response_

### Unleash version

4.9.1

### Subscription type

Open source

### Hosting type

Self-hosted

### SDK information (language and version)

_No response_

### PR DESCRIPTION
**Pull request by wilcoschoneveld**
## About the changes

When not supplying a username or password to email options it will now default to empty string for both.
Also added a new optional argument called `transportOptions` to allow users to configure SMTP in more detail.

Closes #1583.

### Important files

`email-service.ts`

## Discussion points

Not sure if using empty string (`''`) for auth works like expected, but in our smtp server (which has no auth configured) this seems to work.

### CODE REVIEW

**Review by chriswk — APPROVED** [review]
This seems reasonable, I'm a bit wary about re-exporting nodemailer types, but seems like a better solution than having to duplicate all the settings they make available so am inclined to Approve.

@ivarconr  / @FredrikOseberg care to chime in?

**Comment by FredrikOseberg** [comment]
[Github PR: Added ability to set additional transport options to email service](https://trello.com/c/GlayffLa/1151-github-pr-added-ability-to-set-additional-transport-options-to-email-service)

**Review by FredrikOseberg — APPROVED** [review]
LGTM

**Comment by chriswk** [comment]
After some internal discussion we're willing to take onboard the types from nodemailer. If they change their types drastically we might need to build a type on the Unleash side with a translation from new arguments. For now, the win with actually supporting all transport options from nodemailer is a bigger win than risk.

**Comment by chriswk** [comment]
Thank you @wilcoschoneveld for this. I'll merge it now, and it will be part of our next release. :+1:

**Comment by wilcoschoneveld** [comment]
Awesome, thanks!

**Pull request merged**
