### PR TITLE
chore: Doc only should skip build

### PR DESCRIPTION
**Pull request by gastonfournier**
## About the changes
This fakes the build on docs-only PRs to be able to have a green build.
Touching a doc to validate it works

### CODE REVIEW

**Review by dgorton — COMMENTED** [review]
I still don't know these build processes. This LGTM, but @thomasheartman has a better chance of spotting any potential issues.

**Comment by gastonfournier** [comment]
> I still don't know these build processes. This LGTM, but @thomasheartman has a better chance of spotting any potential issues.

We'll have to try it with some documentation PR. The fact that this PR modifies an action, triggers the real build process. The good news is, that among the `9 successful checks`, none is the fake build process. This suggests that it'll trigger if and only if the PR is **only** changing documentation (actually this is my main concern: to trigger a fake build for docs that modify both code and docs)

**Comment by gastonfournier** [comment]
This could be tested by merging this PR and then rebasing on https://github.com/Unleash/unleash/pull/4821

**Review by ivarconr — APPROVED** [review]
Nice 👍🙂

**Review by thomasheartman — APPROVED** [review]
I like it a lot 😄

**Pull request merged**
