### PR TITLE
Add multiple tags

### PR DESCRIPTION
**Pull request by andreas-unleash**
Add Tag dialog redesign to allow batch add

Some Refactoring

Signed-off-by: andreas-unleash <andreas@getunleash.ai>

## About the changes

Closes [1-611](https://linear.app/unleash/issue/1-611/create-a-auto-complete-component-for-tags)

## Discussion points

https://user-images.githubusercontent.com/104830839/216286897-4e392822-57c2-4e50-a5d8-e89d006b3fa5.mov

### CODE REVIEW

**Comment by sjaanus** [comment]
When having more than 3 tag types, then a scroll appears on the whole modal. Can we have scroll inside the dropdown instead?

image

**Comment by sjaanus** [comment]
When creating a new tag, it is not possible to press "Add tag" button 

[Screencast from 02.02.2023 12:56:38.webm](https://user-images.githubusercontent.com/964450/216306503-2e33cb15-00a6-42c8-9ca7-7c5af2161729.webm)

**Comment by sjaanus** [comment]
When you add multiple tags, it is trying to send all previously added tags to server also. It should send each tag only once.
[Screencast from 02.02.2023 13:26:25.webm](https://user-images.githubusercontent.com/964450/216313078-9318039b-23a0-4d9d-8e6b-3dabcdfce1a8.webm)

**Review by sjaanus — CHANGES_REQUESTED** [review]
```
this.route({
            method: 'post',
            path: '',
            handler: this.createTag,
            permission: UPDATE_FEATURE,
            middleware: [
                openApiService.validPath({
                    tags: ['Tags'],
                    operationId: 'createTag',
                    responses: {
                        201: resourceCreatedResponseSchema(
                            'tagWithVersionSchema',
                        ),
                    },
                    requestBody: createRequestSchema('tagSchema'),
                }),
            ],
        });
```

is causing error on db query. we need to remove the permission or replace it with something

**Comment by andreas-unleash** [comment]
@sjaanus I think I got all your points covered. Please let me know if I missed anything

**Comment by sjaanus** [comment]
> ```
> this.route({
>             method: 'post',
>             path: '',
>             handler: this.createTag,
>             permission: UPDATE_FEATURE,
>             middleware: [
>                 openApiService.validPath({
>                     tags: ['Tags'],
>                     operationId: 'createTag',
>                     responses: {
>                         201: resourceCreatedResponseSchema(
>                             'tagWithVersionSchema',
>                         ),
>                     },
>                     requestBody: createRequestSchema('tagSchema'),
>                 }),
>             ],
>         });
> ```
> 
> is causing error on db query. we need to remove the permission or replace it with something

UI looking good! Only this one I am worried about. Maybe we can get rid of this nasty exception

```
[2023-02-03T09:51:06.178] [ERROR] feature-toggle-store.ts - Error: Undefined binding(s) detected when compiling FIRST. Undefined column(s): [name] query: select "project" from "features" where "name" = ? limit ?
    at Object.queryBuilder (/home/jaanus/Git/unleash/node_modules/knex/lib/knex-builder/make-knex.js:111:26)
    at Function.value (/home/jaanus/Git/unleash/node_modules/knex/lib/knex-builder/make-knex.js:91:29)
    at Function.knex.<computed> [as first] (/home/jaanus/Git/unleash/node_modules/knex/lib/knex-builder/make-knex.js:265:28)
    at FeatureToggleStore.getProjectId (/home/jaanus/Git/unleash/dist/lib/db/feature-toggle-store.js:94:14)
    at IncomingMessage.req.checkRbac (/home/jaanus/Git/unleash/dist/lib/middleware/rbac-middleware.js:35:54)
    at /home/jaanus/Git/unleash/dist/lib/routes/controller.js:15:37
    at Layer.handle [as handle_request] (/home/jaanus/Git/unleash/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/jaanus/Git/unleash/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/jaanus/Git/unleash/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/jaanus/Git/unleash/node_modules/express/lib/router/layer.js:95:5)
    at /home/jaanus/Git/unleash/node_modules/express/lib/router/index.js:284:15

```

**Review by sjaanus — APPROVED** [review]
LGTM!

**Pull request merged**
