### PR TITLE
chore: incoming webhooks and tokens migration

### PR DESCRIPTION
**Pull request by nunogois**
https://linear.app/unleash/issue/2-1699/db-create-migration-for-a-new-incoming-webhooks-table

Adds a migration that creates 2 tables:
 - `incoming_webhooks`
 - `incoming_webhook_tokens`

### CODE REVIEW

**Review by chriswk — COMMENTED** [review]
I'm not sure we want to cascade here. 

Unless the thought is that incoming webhooks are strongly bound to the user that created them?

I see both pros and contras here. 
Pros:
- explicit control over what webhooks are created by whom
- automatic cleanup when users are removed from the system

Cons:
- automatic cleanup when users are removed. This is a double-edged sword, and the one that worries me the most

**Comment by chriswk** [comment]
Ah, I forgot about the soft delete thing. May I also suggest an index on the created_by_user_id?

**Comment by chriswk** [comment]
Never mind, I see they are in place already.

**Comment by chriswk** [comment]
You don't need `use strict;` btw, so feel free to remove it :)

**Review by gastonfournier — APPROVED** [review]
LGTM!

**Pull request merged**
