### PR TITLE
fix: Added the ability to specify db-schema via ENV

### PR DESCRIPTION
**Pull request by batazor**

### CODE REVIEW

**Comment by batazor** [comment]
@ivarconr What do you think?

**Review by ivarconr — APPROVED** [review]
Looks good to me! ;D

**Comment by ivarconr** [comment]
Would you mind also add a short notice about the environment name in the [configuring unleash docs](https://github.com/Unleash/unleash/blob/master/docs/configuring-unleash.md)?

**Comment by batazor** [comment]
Yes. I added a short notice about the environment name

**Pull request merged**
