### PR TITLE
chore: replace coveralls with jest coverage for pr builds

### PR DESCRIPTION
**Pull request by aneeshrelan**
Addresses #940

### CODE REVIEW

**Comment by aneeshrelan** [comment]
@ivarconr I was not able to test it completely. Found out act is there to test, but locally getting the following error on running a `act pull_request`. I might be missing something

Have created a draft PR for now

**Comment by ivarconr** [comment]
I approved a run. If more is needed i will take a look tomorrow

**Comment by ivarconr** [comment]
I do not think it has been set up correctly as all e2e tests fails (might be because they need an postgres db?). 

Is it possible to have it just use the reports produced in the previous step instead of running all the test again?

**Comment by aneeshrelan** [comment]
Yep, I saw the docs, it can take a coverage file for parsing. Let me get
that fixed in a while

**Comment by aneeshrelan** [comment]
@ivarconr I've updated the parameters. Moved the test run command to happen via the jest coverage itself using the `test-script` parameter. Please see if that's okay. Let me know if there's anything else and if it's possible to test locally for faster feedback cycle

**Comment by ivarconr** [comment]
Hi again @aneeshrelan 

So the test are now not running at all because it is missing the dependencies. 

The output:

```sh
/usr/local/bin/yarn run test:coverage
yarn run v1.22.11
$ NODE_ENV=test PORT=4243 jest --coverage --forceExit
/bin/sh: 1: jest: not found
error Command failed with exit code 127.
```

**Comment by aneeshrelan** [comment]
Thanks @ivarconr  for the logs, I'll check this one. Also, I was not able to run the `yarn run test:coverage` command locally. I had a few failures. I was looking to find out the test coverage report path so that I can pass that directly to the jest action instead of running it again

**Comment by ivarconr** [comment]
any updates @aneeshrelan ?

**Comment by aneeshrelan** [comment]
Didn't get a chance to look at this @ivarconr 

One way is to do a `yarn` again before doing a `yarn run test:coverage` in the jest action.

The other is to give the generated report from the existing test action (as on `master`), but we'll also need to store the coverage report from `master` as an artifact to compare with PRs. What do you suggest?

**Comment by ivarconr** [comment]
I moved it to a separate action. I see that an external PR will not be allowed to post back, so merging to continue testing separately.

**Comment by ivarconr** [comment]
Its still failing though. Unsure how to fix this.

@aneeshrelan @chriswk ideas?

```
Could not read report file located at report.json [Error: ENOENT: no such file or directory, open 'report.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'report.json'
}
Error: ❌ The test suite failed. Please, check the console output for more details.
```

**Comment by aneeshrelan** [comment]
Do you get the report file created when you run the `test:coverage` command locally?

**Comment by ivarconr** [comment]
I changed it to "test:coverage:jest" for this action. It does not look like it generate any coverage file. Will delete coverage folder to be sure".

**Comment by ivarconr** [comment]
I tried to use the one called out in the docs:
https://github.com/marketplace/actions/jest-coverage-report#customizing-test-script

**Comment by aneeshrelan** [comment]
Oh okay. Weird! Because in the same docs it says to refer to an existing JSON report if available

https://github.com/marketplace/actions/jest-coverage-report#use-existing-test-reports

**Pull request merged**
