### PR TITLE
Refactor: move openapi utils into /util directory

### PR DESCRIPTION
**Pull request by thomasheartman**
As discussed in #1754, this change extracts some of the functions from the OpenAPI index file and puts them into a dedicated `util` directory.

### CODE REVIEW

**Review by olav — CHANGES_REQUESTED** [review]
Great! Should we move some of the tests in `openapi/index.test.ts` as well?

Could move them into files like `utils/create-request-schema.test.ts`.

**Comment by thomasheartman** [comment]
Makes sense! Will fix 🙋🏼

**Review by nunogois — APPROVED** [review]
Can't think of a strong argument why `create-request-schema` and `create-response-schema` shouldn't be exported from `openapi/index.ts` in order to simplify imports, but still, this LGTM.

**Comment by thomasheartman** [comment]
@nunogois Aye, fair. I suggested that in [one of the threads on #1754](https://github.com/Unleash/unleash/pull/1754#discussion_r909661824), but Olav felt it wasn't necessary. I have no strong opinions either way, but would be happy to re-export later if we decide to do that 💁🏼 Thanks 😄

**Pull request merged**
