### PR TITLE
Wrong number on the project page regarding members in that project

### PR DESCRIPTION
**Pull request by sjaanus**
Co-Authored by @nunogois .

This PR fixes the number on project page. Also it adds members in group to the count.

### CODE REVIEW

**Review by nunogois — APPROVED** [review]
LGTM, but it might be a good idea to have someone more experienced with this have a look as well before merging.

**Review by sighphyre — COMMENTED** [review]
Code looks good but I have a domain question here - this looks like it changes the results for the default project by excluding the root role. Historically, the default project includes all users though a hidden editor role. I'm okay with changing that but I think we need some inputs from the UX folks before we do. WDYT?

**Comment by sjaanus** [comment]
Added new logic and now members are counted from these rules:

1. All the users and groups that are seen on access tab under project
2. All the global editors

Global admins/viewers are not included.

**Review by sighphyre — APPROVED** [review]
LGTM!

**Pull request merged**
