### PR TITLE
fix: convert AUTH_TYPE to uppercase

### PR DESCRIPTION
**Pull request by ivarconr**

### CODE REVIEW

**Review by chriswk — APPROVED** [review]
LGTM :)

**Comment by ivarconr** [comment]
this does not solve the case when users sends options problematically. Can enums in typescript solve this automatically @chriswk ?

**Comment by chriswk** [comment]
> this does not solve the case when users sends options problematically. Can enums in typescript solve this automatically @chriswk ?

problematically? as in not a valid enum value? or did you mean programmatically?

**Comment by chriswk** [comment]
I smell a missing test

**Comment by ivarconr** [comment]
programmatically

**Comment by chriswk** [comment]
I'll get a test going

**Pull request merged**
