### PR TITLE
fix: date should sort asc/desc properly

### PR DESCRIPTION
**Pull request by sjaanus**
Now date field will sort correctly, when arrow down, it is descending, and when arrow up, it is ascending.
I suspect this is a bug in react table v7.

Old broken:
image

New:
image

### CODE REVIEW

**Review by Tymek — COMMENTED** [review]
How about other tables? I think we need to keep it consistent

**Comment by FredrikOseberg** [comment]
> How about other tables? I think we need to keep it consistent

We should keep consistency across tables.

**Comment by sjaanus** [comment]
> How about other tables? I think we need to keep it consistent

Yes, added for all tables now

**Comment by sjaanus** [comment]
> > How about other tables? I think we need to keep it consistent
> 
> We should keep consistency across tables.

Added for all tables now

**Review by FredrikOseberg — APPROVED** [review]
LGTM

**Review by Tymek — APPROVED** [review]

**Pull request merged**
