### PR TITLE
docs: remove the proxy from the sdks overview table

### PR DESCRIPTION
**Pull request by thomasheartman**
## What

This change removes the "unleash proxy" column from the SDK compat table.

## Why

Because the proxy isn't technically an SDK. Having the column there can be misleading to users.

In the latest case, a user pointed out that the table says the proxy supports `isEnabled` with fallback values, but that there is no way to use this via the API (or via client-side sdks) at the moment.

I think we should add a section to the proxy doc about its capabilities instead.

In fact, I think we should do the same thing with the proxy that we did with the SDKs: merge the docs.getunleash content with the github readme and instead source it from there.

### CODE REVIEW

**Comment by sighphyre** [comment]
Yeah I think this is the right thing to do. Do we have a plan to put this info somewhere else or does it not really make sense?

**Comment by ivarconr** [comment]
I see your point, but I think we can cause some confusion on what the frontend SDKs will support.

**Comment by thomasheartman** [comment]
@ivarconr 
> I see your point, but I think we can cause some confusion on what the frontend SDKs will support.
Could you elaborate on that? I'm not sure I understand.

**Comment by thomasheartman** [comment]
As mentioned in the description, the content from this repo's proxy docs have been added to the proxy readme in https://github.com/Unleash/unleash-proxy/pull/116. [This commit adds a section about capabilities](https://github.com/Unleash/unleash-proxy/commit/a86f9c56a8c7282ce1a8209c79a28b4775873f24) so that they don't get lost.

**Comment by ivarconr** [comment]
> Could you elaborate on that? I'm not sure I understand.

I'm happy with merging this if we also creates an issue to create a simoil if we create an issue to establish a similar table for frontend SDKs. Some capabilities will be automatically inherited from the proxy (e.g. constraints, ip range etc). 

This would also make it easier to highlight differences in frontend SDK capabilites (bootstrap, impression events etc). 

@thomasheartman

**Review by ivarconr — APPROVED** [review]

**Comment by thomasheartman** [comment]
Yeah, I think that's fair (and honestly, it's pretty overdue 😅).  Issue created in #3179

**Pull request merged**
