### PR TITLE
fix: containers for node 16, 18 and 20

### PR DESCRIPTION
**Pull request by ivarconr**
Will produce docker images for node 16, 18 and 20.

Related to #1265.

## About the changes

Closes #

### CODE REVIEW

**Review by chriswk — CHANGES_REQUESTED** [review]
This won't work. It will have a race condition on which part of the matrix finishes last for which container actually gets pushed. If you're going to do multiple platforms, you'll need to extend our tag format. 

This will build the same container, pushing to the same tag for all three containers.

Unfortunately, build-args is not a differentiator.

**Comment by chriswk** [comment]
Adding a <nodeversion> suffix or prefix to our tags would work. Why do we need to do this though? I agree with building for multiple node versions and confirming that they work, but for docker I'm not a 100% sure why we want to publish multiple version?

**Comment by ivarconr** [comment]
> I agree with building for multiple node versions and confirming that they work, but for docker I'm not a 100% sure why we want to publish multiple version?

Its a fair question. The main motivation is that changing the default node version would (in theory?) be a breaking change, while we should start to offer versions for people who wants to start using node-18 today.

**Review by chriswk — COMMENTED** [review]
Is 20-alpine out?

**Pull request closed without merging**
