### PR TITLE
Fix: Add support for IPC connections.

### PR DESCRIPTION
**Pull request by ivarconr**
Read this for more details:
https://nodejs.org/api/net.html#net_identifying_paths_for_ipc_connections

### CODE REVIEW

**Comment by ivarconr** [comment]
@A142838 You can now define the option 'pipe', which is used to identify a IPC endpoint / UNIX socket / Windows pipe. 

Are you able to confirm that this will solve your issue?

**Comment by A142838** [comment]
@ivarconr yes it does work with the fix Thanks so much for addressing it quickly

**Comment by ivarconr** [comment]
released as `3.2.6`.

**Comment by A142838** [comment]
Awesome ....best OSS experience for me.

**Pull request merged**
