### PR TITLE
chore: This helps output the migrations being applied

### PR DESCRIPTION
**Pull request by gastonfournier**
## About the changes
This outputs to console.log but should be indexable:
image

### CODE REVIEW

**Review by gardleopard — APPROVED** [review]
LGTM

**Review by gardleopard — CHANGES_REQUESTED** [review]
lets think about it, might be to much information

**Comment by gastonfournier** [comment]
> Might be to noisy maybe we should not??

Sure, this is the type of thing to consider. You only get the migrations that are applied, if your DB is up-to-date with the migration you get this instead:
image

So we should only see the log of the migrations applied by the pod running the migrations. The others should just print something like above

**Review by gardleopard — APPROVED** [review]
then its good for me

**Pull request merged**
