### PR TITLE
fix: session fetching should not crash application  when db is unavil…

### PR DESCRIPTION
**Pull request by ivarconr**
…able

### CODE REVIEW

**Comment by ivarconr** [comment]
We might alos want to contribute a patch back to connect-session-knex:
https://github.com/gx0r/connect-session-knex/issues/72

**Review by chriswk — APPROVED** [review]
Looks good I think, did you manage to have any tests for the new `get` method?

**Comment by ivarconr** [comment]
We also need to add a fix for the dbCleanup code:

```
[ERROR] Error: connect ECONNREFUSED 127.0.0.1:5432
    at createQueryBuilder (/home/ivarconr/code/unleash/node_modules/knex/lib/knex-builder/make-knex.js:313:26)
    at KnexStore.knex (/home/ivarconr/code/unleash/node_modules/knex/lib/knex-builder/make-knex.js:100:12)
    at /home/ivarconr/code/unleash/node_modules/connect-session-knex/lib/index.js:43:10
```

**Review by FredrikOseberg — APPROVED** [review]
LGTM

**Pull request closed without merging**
