### PR TITLE
Remove heroku from e2e tests

### PR DESCRIPTION
**Pull request by sjaanus**
Remove heroku from e2e tests

### CODE REVIEW

**Comment by thomasheartman** [comment]
@sjaanus Is this PR still looking to get merged? It looks relevant (and good) to me.

**Comment by sjaanus** [comment]
> @sjaanus Is this PR still looking to get merged? It looks relevant (and good) to me.

This PR is not fully working. We were working on this with Fredrik, but priorities changes.

We need to work on this eventually.

**Comment by thomasheartman** [comment]
Got it! Should the PR stay open or can it be closed, then? If you want it to stay open, you can add the 'pinned' tag to avoid stale bot trying to close it again 🤓

**Comment by ivarconr** [comment]
Why is this not merged @sjaanus ?

**Comment by sjaanus** [comment]
> Why is this not merged @sjaanus ?

It is not fully finished and in backlog for now. Will need to take a look at it sooner or later.

**Comment by sjaanus** [comment]
Closed for now. Added branch name to linear task.

**Pull request closed without merging**
