### PR TITLE
docs: update to node 18

### PR DESCRIPTION
**Pull request by gastonfournier**
## About the changes
Update documentation to the minimum version of node. This was already updated in other parts of the documentation

### CODE REVIEW

**Review by thomasheartman — APPROVED** [review]
Yeah, I'm good with this change for sure 😄

**Comment by thomasheartman** [comment]
@gastonfournier , I took the liberty of also updating the `engines` property of the website/package.json file. Do you agree with that change?

**Comment by gastonfournier** [comment]
> @gastonfournier , I took the liberty of also updating the `engines` property of the website/package.json file. Do you agree with that change?

Yes, I remember I didn't change this, because the website runs differently than Unleash, so I wasn't sure this change was needed, but if it does work, then better have only one runtime :) thanks!

**Comment by thomasheartman** [comment]
Can't see any reason why it wouldn't work? And if the docs say it requires node 18, then surely we should say that everywhere?

**Comment by gastonfournier** [comment]
> Can't see any reason why it wouldn't work? And if the docs say it requires node 18, then surely we should say that everywhere?

I mean, the website is not run on the same infrastructure as Unleash, actually... I don't know where it's running... but just for the sake of thinking, imagine this is running in say Vercel, and Vercel does not support node 18 yet (or it can be a docker container that needs to switch its image from node-16 to node-18). Let me know if I'm speaking nonsense (sometimes I do, specially in the early morning :laughing:)

**Comment by thomasheartman** [comment]
No, I think it makes sense, and I think I'm the one who's speaking nonsense 😄 I didn't read the PR closely enough and thought you were adjusting the docs for the docs 😅 I realize now that it's the docs for the application and that "docs: update to node 18" doesn't mean "update the docs to 18" but "update the docs to say that the app needs 18+". 

Sooo ... yeah. If you want to, we can remove that commit, but it seems that the build has worked just fine, so I see no reason not to do it?

**Comment by gastonfournier** [comment]
> it seems that the build has worked just fine, so I see no reason not to do it?

Exactly! Let's do it, we can revert if we find some issue down the road :+1:

**Pull request merged**
