### PR TITLE
feat: update rate-limit

### PR DESCRIPTION
**Pull request by nunogois**
https://linear.app/unleash/issue/2-732/rate-limit-auth-endpoints-in-enterprise

Updates the rate-limit to reflect the [recent rate-limiting in Enterprise](https://github.com/ivarconr/unleash-enterprise/pull/381).

### CODE REVIEW

**Review by gastonfournier — APPROVED** [review]
:+1:

**Review by gastonfournier — CHANGES_REQUESTED** [review]
Should it be minutes to millis?

**Comment by nunogois** [comment]
> Should it be minutes to millis?

In order to reflect what we did for Enterprise it should be `secondsToMilliseconds`, right? 5/second.

https://github.com/ivarconr/unleash-enterprise/pull/381/files#diff-5a84646f18b1bd79726d6e3cfa75cac5c1a92663dde2ec7ba98c43a0cf99b866R39

**Review by gastonfournier — APPROVED** [review]
:+1:

**Comment by nunogois** [comment]
Changes to 10 rpm instead since we were not taking the rate-limiter logic into consideration. See: https://unleash-internal.slack.com/archives/C046LV85N3C/p1677842820424519?thread_ts=1677841764.755599&cid=C046LV85N3C

**Review by sjaanus — APPROVED** [review]

**Pull request merged**
