### PR TITLE
test: meta schema rules should not check description on ref

### PR DESCRIPTION
**Pull request by kwasniew**
## About the changes

Our meta rules checker will only verify description is present when the field is not a ref based field which has its own description.

This change automatically fixes a few schemas.

### CODE REVIEW

**Review by gastonfournier — APPROVED** [review]
LGTM! :rocket:

**Comment by thomasheartman** [comment]
I'm not sure I'm on board with changing these schemas. Have you confirmed that `$ref` descriptions get propagated correctly (in swagger UI etc)? Second, even if they do, you will sometimes want a separate description where they are referenced, so I'm not sure I agree with just removing the descriptions where you have. Have you checked what the descriptions say up against what the $ref.descriptions say?

**Comment by kwasniew** [comment]
The ones I removed are the ones I added a few hours ago myself so I know they are duplicates. I did some experimentation and $ref from the included schema are the ones being shown while the description on the including side was ignored. So we're removing stuff that was already ignored.

**Comment by thomasheartman** [comment]
Got it. In that case it sounds like a definite win! Good work! 🙌🏼

**Pull request merged**
