### PR TITLE
feat: only display oss included projects/environments when install is oss

### PR DESCRIPTION
**Pull request by chriswk**
Trying again, now with a tested function for resolvingIsOss.

Still want to test this on a pro instance in sandbox before we deploy this to our customers to avoid what happened Friday.

### CODE REVIEW

**Review by gastonfournier — COMMENTED** [review]
Can we add a feature flag to release it in a more controlled way and validate in prod?

**Comment by chriswk** [comment]
Will update this to not filter the client-features query. Let's not mess with SDK results

**Comment by chriswk** [comment]
> Can we add a feature flag to release it in a more controlled way and validate in prod?

Yes. If you can turn the entire thing off with a feature flag though it defeats the purpose of the limitation, which is why I did not add a feature flag for this initially.

**Comment by gastonfournier** [comment]
> > Can we add a feature flag to release it in a more controlled way and validate in prod?
> 
> Yes. If you can turn the entire thing off with a feature flag though it defeats the purpose of the limitation, which is why I did not add a feature flag for this initially.

makes sense

**Review by gastonfournier — APPROVED** [review]
LGTM! We'll test carefully before releasing

**Review by gastonfournier — APPROVED** [review]
LGTM!

**Pull request merged**
