### PR TITLE
Upgrade deps2

### PR DESCRIPTION
**Pull request by ivarconr**

### CODE REVIEW

**Comment by ivarconr** [comment]
So I was to quick on the rebase thing on the prev. branch, and lost my history. 

@SimenB would you mind re-commiting the prettier update to this branch. What command do you use to update all the files?

**Comment by SimenB** [comment]
The changes LGTM :)

You don't wanna format non-js?

**Comment by ivarconr** [comment]
Format it all

**Comment by SimenB** [comment]
```
yarn prettier `fd -e md -e json -e css -e html -e yml --hidden` --write
```

`fd`: https://github.com/sharkdp/fd

Should also update the husky config to autorun prettier on commit 🙂

**Comment by SimenB** [comment]
You might want the prettier config I added as well 🙂 At least the single quotes one

image

**Pull request merged**
