### PR TITLE
chore(workflows): update with new branch names

### PR DESCRIPTION
**Pull request by thomasheartman**
this includes updating what I understand to be the destination branch for documentation. This may require some extra updates. Would love some input on this so I don't mess it up 🙋

### CODE REVIEW

**Comment by thomasheartman** [comment]
[Rename GitHub default branches from master to main](https://trello.com/c/Ey6olr8s/669-rename-github-default-branches-from-master-to-main)

**Review by chriswk — APPROVED** [review]
LGTM

**Comment by thomasheartman** [comment]
@chriswk Sweet, thanks! I'll get on it then. Just a quick Q first: should we update https://github.com/Unleash/unleash.github.io first as it's listed as the docs target?

**Comment by thomasheartman** [comment]
Wait ... it's not listed? Unless that's in the yarn deploy command. Hmm 🤔

**Comment by chriswk** [comment]
It's set in the docusaurus config. I believe that deploys to gh-pages. So you shouldn't need to change that

**Pull request merged**
