### PR TITLE
task: Removed edge bulk metrics endpoint

### PR DESCRIPTION
**Pull request by chriswk**
Removes /edge/metrics. This has been superseded by /api/client/metrics/bulk. Once this is merged, Unleash 6.0 will require Edge > 17.0.0. (We recommend at least v19.1.3)

### CODE REVIEW

**Review by gastonfournier — COMMENTED** [review]
Do we need to wait? I mean, as soon as we merge and deploy this, client's on v5 will also need edge +17

**Comment by chriswk** [comment]
It has been disabled for pro customers since April 15th

**Comment by chriswk** [comment]
Enterprise customers will not get this until we actually release v6.

**Review by gastonfournier — APPROVED** [review]
LGTM! Just checked your comments :+1:

**Comment by gastonfournier** [comment]
Just checked with Ivar this is good to go because of your comments, so I'll continue to merge this one

**Pull request merged**
