### PR TITLE
Add ngx-unleash-proxy-client to community sdks

### PR DESCRIPTION
**Pull request by snowfrogdev**

### CODE REVIEW

**Review by chriswk — APPROVED** [review]
Cool. Thank you

**Review by thomasheartman — CHANGES_REQUESTED** [review]
Nice one! Just one request: could you place in between 'minds[...]' and 'pmb0[...]' so that the list stays sorted alphabetically? ☺️

**Review by thomasheartman — APPROVED** [review]

**Comment by thomasheartman** [comment]
@snowfrogdev Cool! Just a question: any reason why you chose the link to npm instead of the link to GitHub? Most other SDKs link to the source code. I noticed that the readme on npm (nice work there! 🙌🏼 ) wasn't on GitHub, so maybe that's why?

**Comment by snowfrogdev** [comment]
No reason really. Le library is inside a monorepo but I can still link to it. https://github.com/snowfrogdev/snowfrogdev/tree/main/packages/ngx-unleash-proxy-client

Would you rather I do that instead?

**Comment by thomasheartman** [comment]
Got it! In that case, yeah, if you don't mind? ☺️ Just to stay consistent with the majority of the other SDKs in there.

**Comment by ivarconr** [comment]
Hi @snowfrogdev, I noticed in the [README.md](https://github.com/snowfrogdev/snowfrogdev/blob/main/packages/ngx-unleash-proxy-client/README.md) it says

```
npm install ngx-unleash-proxy-client
```

But should it not be:

```
npm install @snowfrog/ngx-unleash-proxy-client
```

**Comment by snowfrogdev** [comment]
> Hi @snowfrogdev, I noticed in the [README.md](https://github.com/snowfrogdev/snowfrogdev/blob/main/packages/ngx-unleash-proxy-client/README.md) it says
> 
> ```
> npm install ngx-unleash-proxy-client
> ```
> 
> But should it not be:
> 
> ```
> npm install @snowfrog/ngx-unleash-proxy-client
> ```

Absolutely correct. I will make the fix. Thank you for noticing that.

**Pull request merged**
