### PR TITLE
fix: openapi-service.ts - Invalid response: schema: '#/components/schemas/clientFeaturesSchema

### PR DESCRIPTION
**Pull request by vctqs1**
## About the changes

```
[2023-01-20T03:56:35.912] [DEBUG] openapi-service.ts - Invalid response: {
  schema: '#/components/schemas/clientFeaturesSchema',
  errors: [
    {
      instancePath: '/features/0',
      schemaPath: '#/additionalProperties',
      keyword: 'additionalProperties',
      params: [Object],
      message: 'must NOT have additional properties'
    }
  ]
}
```

and based on resp example in docs https://docs.getunleash.io/reference/api/unleash/export
```
{
  "version": 0,
  "features": [
    {
      "name": "string",
      "type": "string",
      "description": "string",
      "archived": true,
      "project": "string",
      "enabled": true,
      "stale": true,
      "favorite": true,
      "impressionData": true,
      "createdAt": "2023-01-27",
      "archivedAt": "2023-01-27",
      "lastSeenAt": "2023-01-27",
      "environments": [
        {
          "name": "string",
          "type": "string",
          "enabled": true,
          "protected": true,
          "sortOrder": 0,
          "projectCount": 0,
          "apiTokenCount": 0,
          "enabledToggleCount": 0
        }
      ],
      "strategies": [
        {
          "id": "string",
          "name": "string",
          "sortOrder": 0,
          "segments": [
            0
          ],
          "constraints": [
            {
              "contextName": "appName",
              "operator": "NOT_IN",
              "caseInsensitive": false,
              "inverted": false,
              "values": [
                "string"
              ],
              "value": "string"
            }
          ],
          "parameters": {}
        }
      ],
      "variants": [
        {
          "name": "string",
          "weight": 0,
          "weightType": "string",
          "stickiness": "string",
          "payload": {
            "type": "string",
            "value": "string"
          },
          "overrides": [
            {
              "contextName": "string",
              "values": [
                "string"
              ]
            }
          ]
        }
      ],
      "tags": [
        {
          "value": "string",
          "type": "string"
        }
      ]
    }
  ],
  "strategies": [
    {
      "name": "string",
      "displayName": "string",
      "description": "string",
      "editable": true,
      "deprecated": true,
      "parameters": [
        {
          "name": "string",
          "type": "string",
          "description": "string",
          "required": true
        }
      ]
    }
  ],
  "tags": [
    {
      "value": "string",
      "type": "string"
    }
  ],
  "tagTypes": [
    {
      "name": "string",
      "description": "string",
      "icon": "string"
    }
  ],
  "featureTags": [
    {
      "featureName": "string",
      "tagType": "string",
      "tagValue": "string",
      "type": "string",
      "value": "string"
    }
  ],
  "projects": [
    {
      "id": "string",
      "name": "string",
      "description": "string",
      "health": 0,
      "featureCount": 0,
      "memberCount": 0,
      "createdAt": "2023-01-27",
      "updatedAt": "2023-01-27",
      "changeRequestsEnabled": true,
      "favorite": true
    }
  ],
  "featureStrategies": [
    {
      "id": "string",
      "name": "string",
      "sortOrder": 0,
      "segments": [
        0
      ],
      "constraints": [
        {
          "contextName": "appName",
          "operator": "NOT_IN",
          "caseInsensitive": false,
          "inverted": false,
          "values": [
            "string"
          ],
          "value": "string"
        }
      ],
      "parameters": {}
    }
  ],
  "featureEnvironments": [
    {
      "name": "string",
      "environment": "string",
      "type": "string",
      "enabled": true,
      "strategies": [
        {
          "id": "string",
          "featureName": "string",
          "projectId": "string",
          "environment": "string",
          "strategyName": "string",
          "sortOrder": 0,
          "createdAt": "2023-01-27",
          "constraints": [
            {
              "contextName": "appName",
              "operator": "NOT_IN",
              "caseInsensitive": false,
              "inverted": false,
              "values": [
                "string"
              ],
              "value": "string"
            }
          ],
          "parameters": {}
        }
      ]
    }
  ],
  "environments": [
    {
      "name": "string",
      "type": "string",
      "enabled": true,
      "protected": true,
      "sortOrder": 0,
      "projectCount": 0,
      "apiTokenCount": 0,
      "enabledToggleCount": 0
    }
  ],
  "segments": [
    {
      "id": 0,
      "name": "string",
      "description": "string",
      "constraints": [
        {
          "contextName": "appName",
          "operator": "NOT_IN",
          "caseInsensitive": false,
          "inverted": false,
          "values": [
            "string"
          ],
          "value": "string"
        }
      ]
    }
  ],
  "featureStrategySegments": [
    {
      "segmentId": 0,
      "featureStrategyId": "string"
    }
  ]
}
```

I saw that it is missed `tags`, `archived`, `archivedAt` and `favorite` property
then double check in src code and see 
- favorite property: https://github.com/vctqs1/unleash/blob/main/src/lib/db/feature-toggle-client-store.ts#L214
- tags via this function https://github.com/vctqs1/unleash/blob/main/src/lib/db/feature-toggle-client-store.ts#L201
- `archived` and `archivedAt`: saw that it was ejected in src code, but just add in cases follow document

### CODE REVIEW

**Comment by vctqs1** [comment]
sorry for bothering you, could u help guide, how to unlock these steps?
image

**Comment by Tymek** [comment]
I think this is optional for your changes. I'll take a look at the PR

**Comment by Tymek** [comment]
I think `clientFeatureSchema` is something different. It should not have favorites. We have `src/lib/openapi/spec/feature-schema.ts` we use in UI, and client API is for SDKs. I'll check what's the reason for OpenAPI warning.

**Comment by vctqs1** [comment]
> I think `clientFeatureSchema` is something different. It should not have favorites. We have `src/lib/openapi/spec/feature-schema.ts` we use in UI, and client API is for SDKs. I'll check what's the reason for OpenAPI warning.

Yeah, `favorites` actually dont appear in my real resp, but don't know somehow it appears in docs
image

@Tymek should i remove this field?

**Comment by vctqs1** [comment]
@Tymek alright, i think it is mistaken, they're gonna remove favorites field in this PR https://github.com/Unleash/unleash/pull/3061

😂 let me remove it in schema

**Comment by vctqs1** [comment]
@Tymek hi could u help me check this PR, please. Thank you

**Comment by Tymek** [comment]
You are referencing [/api/unleash/export](https://docs.getunleash.io/reference/api/unleash/export), but trying to change `clientFeaturesSchema` and not `featureSchema`. Are you sure changes should be made to "Client" API schema? Please provide more detailed explanation of what request is triggering original warning. We are in the process of refactoring OpenAPI, adding details about error handling, and splitting request and response schema definitions, so getting rid of "Invalid response" warnings has high priority.

**Comment by vctqs1** [comment]
@Tymek hi,
it's `getAllToggles` in [admin-api](https://github.com/vctqs1/unleash/blob/main/src/lib/routes/admin-api/feature.ts#L80). the step by step look like below
- getAllToggles -> call [await this.service.getFeatureToggles](https://github.com/vctqs1/unleash/blob/main/src/lib/routes/admin-api/feature.ts#L187)
- this.service.getFeatureToggles -> call **to client store service** [this.featureToggleClientStore.getAdmin](https://github.com/vctqs1/unleash/blob/main/src/lib/services/feature-toggle-service.ts#L707)
reference code [here](https://github.com/vctqs1/unleash/blob/main/src/lib/db/feature-toggle-client-store.ts)
```
async getAdmin({
        featureQuery,
        userId,
        archived,
    }: IGetAdminFeatures): Promise<IFeatureToggleClient[]> {
        return this.getAll({ featureQuery, archived, isAdmin: true, userId });
    }
```
in `this.getAll` it will check if this is `isAdmin = true`. it will inject query to get tags and other things 
image

**Comment by vctqs1** [comment]
@Tymek hi could help have alook, thank you

**Comment by vctqs1** [comment]
@Tymek hi could u help check my explantion, it propmts alot of warning in our cloud

**Comment by Tymek** [comment]
Sorry for the delay. This is probably related: https://github.com/Unleash/unleash/pull/3277

**Comment by Tymek** [comment]
@vctqs1 Please try running a version with this change:
https://github.com/Unleash/unleash/pull/3284

After internal discussion we decided to clean up the service data according to the OpenAPI spec. In case you encounter further issues, please let us know using the issue template. I hope this solves you issue.

**Comment by kwasniew** [comment]
@vctqs1 Please not this cleanup is gonna be behind a feature flag for now. Once we confirm it doesn't break any of our clients we can make it available without a flag

**Pull request closed without merging**
