### PR TITLE
client applications

### PR DESCRIPTION
**Pull request by sveisvei**
cc @ivarconr

### CODE REVIEW

**Comment by ivarconr** [comment]
Looks good. 

- A client registration request should insert a new application if it does not exist. 
- Do we need client_strategies or could we just move the strategies colmn to this table?
- must remember to update https://github.com/Unleash/unleash/blob/master/docs/database-schema.md

**Comment by sveisvei** [comment]
1) indeed
2) @ivarconr  What was the initial plan for the client_strategies table? I agree it makes sense to merge based on what I know...

**Comment by ivarconr** [comment]
the initial idea was to keep known strategies for clients somewhere. I don't see any reason to keep this in a separate table. I was not thinking about any other metadata needs when i created that table.

**Comment by ivarconr** [comment]
You want to fetch strategies for an application when fetching details about an application anyway!

**Comment by sveisvei** [comment]
Any way to clean up all migrations?

**Comment by ivarconr** [comment]
I believe the only important thing is that the name of the javascript-file needs to be the same. I was thinking just to inline all the sql's in the javascript files. And from now on we can stick to the db-migrate format, which is easy to generate with db-migrate. 

Need to test though.

**Pull request merged**
