### PR TITLE
Adds an option to allow cors

### PR DESCRIPTION
**Pull request by ashishkujoy**
For using unleash from browser we need to make request to /client/features which are gets failed due to CORS.
This PR provides option to configure CORS

### CODE REVIEW

**Comment by ivarconr** [comment]
Hi, thanks for your suggestion! Unleash is usually not recommended to be used directly from the browser for multiple reasons discussed in #414

You can register the `cors` middleware yourself via a [preRouterHook](https://unleash.github.io/docs/getting_started#2-or-programmatically).

Would that satisfy your needs?

**Comment by ashishkujoy** [comment]
> Hi, thanks for your suggestion! Unleash is usually not recommended to be used directly from the browser for multiple reasons discussed in #414
> 
> You can register the `cors` middleware yourself via a [preRouterHook](https://unleash.github.io/docs/getting_started#2-or-programmatically).
> 
> Would that satisfy your needs?

Thanks For response, i was able to allow CORS using preHook(instead of preRouterHook)

**Comment by diegoNutmeg** [comment]
@ashishkujoy Could you share a snippet of how you achieve the cors config using `preHook`?

**Comment by ashishkujoy** [comment]
@diegoNutmeg I no longer have access to that code neither do I remember how exactly I have made it, I will try that over weekend and will post that.

**Comment by ashishkujoy** [comment]
@diegoNutmeg here is the snippet.
```javascript
const unleash = require('unleash-server');
const cors = require('cors');
const crossOriginMiddleware = (app) => app.use(cors())
unleash
  .start({
    databaseUrl: 'postgres://dummyuser:dummypassword@localhost:5432/unleash',
    port: 4242,
    preHook: crossOriginMiddleware
  })
  .then(unleash => {
    console.log(
      `Unleash started on http://localhost:${unleash.app.get('port')}`,
    );
  });
```

**Comment by diegoNutmeg** [comment]
@ashishkujoy legend 🚀
I will try tomorrow to enable it

**Pull request closed without merging**
