### PR TITLE
docs: update php compatibility matrix table

### PR DESCRIPTION
**Pull request by RikudouSage**
Fixed some stuff.

- async initialization is not supported as php is mostly used synchronously
- due to the above the `Can block until synchronized` is supported
- bootstrap support has been added, file and custom implementation

I have one question: the library doesn't provide its own http request library but requires an abstraction based on `psr/http-client` (this is a php standard based on interoperability of multiple libraries). List of all libraries implementing this can be found [here](https://packagist.org/providers/psr/http-client-implementation).

Now to the question, many of those libraries (including the most popular one, [guzzlehttp/guzzle](https://packagist.org/packages/guzzlehttp/guzzle)) support passing middlewares and thus by proxy this package supports `Category: Custom Headers - function` - should it be marked as supported even if it's not a native feature of the sdk but rather of the underlying library (which is not necessarily installed because anyone can install whatever http client implementation they want)?

@ivarconr What do you think?

### CODE REVIEW

**Comment by ivarconr** [comment]
> Should it be marked as supported even if it's not a native feature of the sdk but rather of the underlying library (which is not necessarily installed because anyone can install whatever http client implementation they want)?

Yes I think it makes sense to mark it as supported. It could also be good with a small example in the readme on how you would solve that with guzzle as an example.

**Review by ivarconr — APPROVED** [review]

**Comment by thomasheartman** [comment]
@RikudouSage Is this ready to go or would you like to make any further changes based on the comments above (i.e. supporting custom headers)? ☺️

**Comment by RikudouSage** [comment]
@thomasheartman Sorry for the delay, now it's ready. Just please check that I resolved the conflicts correctly.

**Comment by thomasheartman** [comment]
@RikudouSage No worries at all (I'd actually forgotten about it 🙈)! But yeah, that looks great to me 😄 I'll merge once it's ready. Thanks 🙏🏼

**Pull request merged**
