### PR TITLE
Open API specification (OAS)

### PR DESCRIPTION
**Pull request by gazconroy**
This is a partial specification that gives an idea of the 'direction of travel'. It just covers Feature Toggles on the server for now but I will extend (if this is something that is still of interest).

I'd like to add more descriptions to the schema objects, it's a bit skimpy at this stage, but that may become self-evident as the rest of the OAS builds.

This particular OAS has no authentication. I've been running unleash-server on localhost (thanks @ivarconr ). Note that to test the 'try it out' features, you may run into [CORS issues](https://swagger.io/docs/open-source-tools/swagger-ui/usage/cors/) (depending on where you host things).

Although, index.html renders the OpenAPI in Swagger UI. It's far from the only such [documentation tool](https://openapi.tools/) but it is the most popular (probably since it's both free and interactive).

### CODE REVIEW

**Comment by ivarconr** [comment]
Thanks. Do you know it is common to provide the swagger-ui as part of the service, or is this typically something hosted elsewhere?

**Comment by gazconroy** [comment]
The Swagger UI JS is usually bundled with the service. It could be hosted elsewhere. The HTML can be embedded in a site or, as has been done in this example, standalone.

**Comment by ivarconr** [comment]
This looks really good. I think this would be a good way to replace what we are currently documenting via the mardown files today. 

There is some things i wonder about:
- is it possible to break down the specification files in to multiple sub-parts, and bundle them as part of the release? 
- we need to provide a default api auth-method for the oss (we already have api keys for the enterprise, we can back-port parts of this i assume). 
- I want to investigate whether we can generate parts of the specification from the joi-schemas. It would be good if we can avoid having to synchronize this manually (but not a strict requirement, the markdown files are fully manual today).

**Comment by gazconroy** [comment]
> This looks really good. I think this would be a good way to replace what we are currently documenting via the mardown files today.

That seems like a sensible approach.

> is it possible to break down the specification files in to multiple sub-parts, and bundle them as part of the release?

For publishing, Open API requires a single file. However, Redocly (for instance) will split an Open API file into component parts to make editing such a large block of monolithic YAML simpler. You need to re-package the components for publishing, mind.

Or do you mean the output? You'll notice the 'tag' breakdowns in the output ('Admin - feature toggles' and 'Admin - archive'): these provide a breakdown in Swagger UI but other systems are better at this (Redocly, again, for instance).

> we need to provide a default api auth-method for the oss (we already have api keys for the enterprise, we can back-port parts of this i assume).

A simple API key authentication would be helpful.

**Comment by gazconroy** [comment]
PR 652 is the one to use

**Pull request closed without merging**
