### PR TITLE
Added Deploy To Digital Ocean Button

### LINKED ISSUE #873: Add a "Deploy to DigitalOcean" Button
https://docs.digitalocean.com/products/app-platform/how-to/add-deploy-do-button/

### PR DESCRIPTION
**Pull request by Patil2099**
Fixes #873

### CODE REVIEW

**Comment by ivarconr** [comment]
Cool! Would we not need a `deploy.template.yaml` as well?

**Comment by Patil2099** [comment]
I wasn't sure about that can you guide me in that.

**Comment by ivarconr** [comment]
Unleash needs a db and that's it. Something like;

```
spec:
  services:
    - name: unleash
      git:
        branch: main
        repo_clone_url: https://github.com/Unleash/unleash.git
    databases:
    - name: unleash-db
````

**Comment by Patil2099** [comment]
I think it is ready now @ivarconr

**Comment by ivarconr** [comment]
> I think it is ready now @ivarconr

Cool. Have you been able to verify it with digital ocean @Patil2099 ?

**Comment by ivarconr** [comment]
image

**Pull request merged**
